# -*- coding: utf-8 -*-
"""7_Numpy_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17wB2WQ2xG4GMKAVOVDEm-yjTZIsdsUTl

# **Excercise 1**
"""

import numpy as np

arr = np.arange(1, 11)

matrix = arr.reshape(2, 5)

print(f"2x5 rehsaped Matrix is :{matrix}")

"""# **Excercise 2**"""

arr = np.arange(1, 21)

extracted_elements = arr[5:15]

print(f"Extracted Elements (Index 5 to 14):{extracted_elements}")

"""# **Excercise 3**"""

import pandas as pd


fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

fruits['pears'] = 4

print(f"Updated Series:{fruits}")

"""# **Excercise 4**"""

data = {
    'name': ['John', 'Alice', 'Bob', 'Emma', 'Raj', 'Liam', 'Sophia', 'David', 'Olivia', 'Mia'],
    'age': [25, 30, 28, 24, 35, 40, 22, 31, 27, 26],
    'gender': ['M', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'F', 'F']
}

df = pd.DataFrame(data)

print(f"DataFrame:{df}")

"""# **Excercise 5**"""

df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

print(f"DataFrame with Occupation Column:{df}")

"""# **Excercise 6**"""

age_30_plus = df[df['age'] >= 30]

print(f"Employees with Age >= 30:{age_30_plus}")

"""# **Excercise 7**"""

df.to_csv('employees.csv', index=False)

df_from_csv = pd.read_csv('employees.csv')

print(f"DataFrame read from CSV:{df_from_csv}")