# -*- coding: utf-8 -*-
"""Conditional and Looping Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9iJ-6MdPC7L0qTk4wYUG6wrjGgyVCK6

#**Question 1**
"""

while True:
  Number = int(input("Enter the number :"))
  if 1<= Number <= 12:
    months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    print(f"The month is {months[Number-1]}")
    break
  else:
    print("Invalid input! Please try again.")

"""#**Question 2**

"""

ticket_price = 6.00
age = int(input("Enter Your Age :"))
if age >= 60 :
  ticket_price = ticket_price / 3
  print(f"You are eligible for a one-third price ticket. Your ticket price is £{ticket_price}")
elif age < 16:
  ticket_price = ticket_price / 2
  print(f"You are eligible for a half price ticket. Your ticket price is £{ticket_price}")
else:
  full_price = ticket_price
  print(f"Your ticket price is £{full_price}.")

"""#**Question 3**

"""

Weight = float(input("Enter Your Weight(in kgs) :"))
Height = float(input("Enter Your Height(in m) :"))
if Weight <= 0 or Height <= 0:
    print("Please enter valid positive numbers for weight and height.")
else:
  BMI = Weight / (Height*Height)
  if BMI < 18.5 :
    Category = "Underweight"
    Direction = "Consider gaining weight to reach a healthier range."
  elif 18.5 <= BMI <= 24.9:
    Category = "Normal"
    Direction = "Great job! Keep maintaining your current weight."
  elif 25 <= BMI <= 29.9:
    Category = "Overweight"
    Direction = "Consider losing weight to improve your health."
  elif 30 <= BMI :
    Category = "Obese"
    Direction = "It's important to work towards a healthier weight range."
  print(f"Your BMI is {BMI:.2f}")
  print(f"You are in the {Category} range. {Direction}, Thank You")

"""#**Question 4**

"""

list1 =[]
greatest = None
for i in range(3):
  num =(float(input("Enter your number :")))
  list1.append(num)
  if greatest == None or num > greatest:
    greatest = num

print(f"Your number are {list1}, and the greatest among them is {greatest} ")

"""#**Question 5**

"""

num = int(input("Enter your number: "))

factorial = 1
if num < 0:
    print("Factorial is not defined for negative numbers.")
elif num == 0 or num == 1:
    factorial = 1
else:
    while num > 1:
        factorial *= num
        num -= 1
print(f"The factorial is {factorial}.")

"""#**Question 6**

"""

num = int(input("Enter a number: "))

reversed_num = 0
while num > 0:
    digit = num % 10
    reversed_num = reversed_num * 10 + digit
    num = num // 10
print(f"The reversed number is: {reversed_num}")

"""#**Question 7**

"""

num = int(input("Enter a number: "))

multiples= []
for i in range(1,11):
  multiples.append(num*i)
print(f"The multiples of {num} are {multiples}")

"""#**Question 8**

"""

while True:
    semi_infinite_loop = input("Enter your value: ")
    print(semi_infinite_loop)
    if semi_infinite_loop.lower() == "done":
        break

"""#**Question 9**


"""

list = []
for i in range(1,11):
  if i % 3 ==0 and i % 5 == 0:
    list.append("FizzBuzz")
  elif i%3 ==0:
    list.append("Fizz")
  elif i% 5 == 0:
    list.append("Buzz")
  else:
    list.append(i)
print(f"The final list is : {list}")

"""#**Question 10**

"""

for i in range(5,0, -1):
  for j in range(i,0,-1):
    print(j, end='')
  print()

