# -*- coding: utf-8 -*-
"""1_Python Fundamentals

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Ycy4lE6dQhhYejDGsEIdFtCzjiJMVB7

# ***Excercise 1***
"""

Student_details = {'Name':'Jacob Thomas Joshy','Student number':'ST0020', 'E-mail':'jacobtjoshy@gmail.com' }
for i in Student_details:
  print(f"{i} : {Student_details.get(i)}")

"""# ***Excercise 2***"""

print("Name : Jacob Thomas Joshy\nStudent number : ST0020\nE-mail : jacobtjoshy@gmail.com")

"""# ***Excercise 3***"""

Maths=[(14,7)]
for (i,j) in Maths:
  Add = i+j
  Subtract = i-j
  Multiply = i*j
  Divide = i/j
  print(f"Addition of the two numbers provide : {Add}\nSubtraction of the numbers provide : {Subtract}\nMultiplication of the numbers provide :{Multiply}\nDivision of the numbers provide :{Divide}")

"""# ***Excercise 4***"""

for i in range(1,6):
  print(i)

"""# ***Excercise 5***"""

print('\"SDK\" stands for \"Software Development Kit\", whereas\n\"IDE\" stands for \"Integrated Development Environment\".')

"""# ***Excercise 6***"""

print("python is an \"awesome\" language.")
print("python\n\t2023")
print('I\'m from Entri.\b')
print("\65")
print("\x65")
print("Entri", "2023", sep="\n")
print("Entri", "2023", sep="\b")
print("Entri", "2023", sep="*", end="\b\b\b\b")

"""# ***Excercise 7***"""

num=23
textnum="57"
decimal=98.3
print(f'num is a {type(num)}\ntextnum is a {type(textnum)}\ndecimal is a{type(decimal)}')
total_sum = num + int(textnum) + decimal
print(f"Sum: {total_sum}\nType of sum: {type(total_sum)}")

"""# ***Excercise 8***"""

days_in_a_year = 365
hours_in_a_day = 24
minutes_in_a_hour = 60
Total_no_of_minutes_in_a_year =  days_in_a_year * hours_in_a_day * minutes_in_a_hour
print(f"There are {Total_no_of_minutes_in_a_year} minutes in a year.")

"""# ***Excercise 9***"""

name =input("Kindly Enter Your Name :")
gender = input("Kindly Enter Your Gender as M/F :")
if gender == "M":
  print(f"Welcome To The Game show, Mr.{name}")
else:
  print(f"Welcome To The Game show, Ms.{name}")

"""# ***Excercise 10***"""

pounds_amount = float(input("Enter the amount in Pounds (£): "))

dollar_amount = pounds_amount * 1.22

print(f"Currently, £{pounds_amount} equals ${dollar_amount}.")

