# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpOyW7nf-c55q1VMzJS7YP0IZihna6Gb

## **Excercise 1**

**What does the len() function do in Python? Write a code example using len() to find the length of a list.**

len() function in python is a built in function returns the number of items in an object. It works with lists, strings, tuples, dictionaries, and other iterable objects.
Items can be anythin like integers, strings, boolean values etc..
"""

#For example
list1 = [1,2,3,'list', 9.0, True]                                 # In case of lists, tuples etc.. it'll count the number of elemenst in them.
print("Number of elements in list1 is :", len(list1))
Greeting = 'Hello Good Morning'                                   # However in case of such type of string variables or objects , it counts the characters.
print("Number of characters in  Greeting(including spaces) is :", len(Greeting))

"""## **Excercise 2**
 **Write a Python function greet(name) that takes a person's name as input and prints "Hello, [name]!".**

"""

def greet(name = None):

  if name is None:
    name = input("Enter your name :").strip()

  name = name.title()

  if not name:
    name = 'Guest'

  print(f"Hello, {name}")

greet("Jake")
greet()

"""## **Excercise 3**
 **Write a Python function find_maximum(numbers) that takes a list of integers and returns the maximum value without using the built-in max() function. Use a loop to iterate through the list and compare values.**

"""

def find_maximum(numbers):
  if not numbers:
    return None

  maximum_value = numbers[0]
  for num in numbers:

    if num > maximum_value:
      maximum_value = num

  return maximum_value

import random as rd

numbers = [rd.randint(1, 100) for _ in range(9)]
print(f"The intial generated list is : {numbers}")

list2 = [rd.randint(-100,100) for _ in range(9)]
print(f"Another generated list to cross-check the function is : {list2}")

print(f"Maximum Number in list Numbers is : {find_maximum(numbers)}")

print(f"Maximum Number in list list2 is : {find_maximum(list2)}")

"""## **Excercise 4**
 **Explain the difference between local and global variables in a Python function. Write a program where a global variable and a local variable have the same name and show how Python differentiates between them.**

 Ans: Global variables are those variables defined outside any function and have a global scope, meaning they can be accessed and modified from anywhere in the script. To acess a global variable inside a function, 'global' keyword is used.
 While local variables are those variables which are defined in a function and do not have global scope. They exist only within that function. Local variable is not accessible anywhere in the script.


"""

message = "I am a global variable"  # This is a global variable and is acessible anywhere in script

def my_function():

    message = "I am a local variable"     # Local Variable
    print("Inside the function:", message)   #This prints only local variable

my_function()
print("Outside the function:", message)  # This prints the global variable

"""## **Excercise 5**
 **Create a function calculate_area(length, width=5) that calculates the area of a rectangle. If only the length is provided, the function should assume the width is 5. Show how the function behaves when called with and without the width argument.**

"""

def calculate_area(length, width=5):

  if length < 0 or width < 0:
        return "Invalid input! Length and width must be non-negative."

  if not width:
    width = 5

  area = length * width
  print(f"The area of the rectangle is : {area} ")

calculate_area(8)
calculate_area(8,10)

