# -*- coding: utf-8 -*-
"""course_catalog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101OfeDKgVAAc4xt_FqL5smOFH_a8dAl8

# **Excercise 1**
"""

# course_catalog.py
class Course:
    def __init__(self, course_code, course_name, credit_hours):

        self.course_code = course_code
        self.course_name = course_name
        self.credit_hours = credit_hours

    def display_course_info(self):

        return f"{self.course_code}: {self.course_name} ({self.credit_hours} credit hours)"

class CoreCourse(Course):
    def __init__(self, course_code, course_name, credit_hours, required_for_major):

        super().__init__(course_code, course_name, credit_hours)
        self.required_for_major = required_for_major

    def display_course_info(self):
        return super().display_course_info() + f" - Required for major: {'Yes' if self.required_for_major else 'No'}"

class ElectiveCourse(Course):
    def __init__(self, course_code, course_name, credit_hours, elective_type):

        super().__init__(course_code, course_name, credit_hours)
        self.elective_type = elective_type

    def display_course_info(self):
        return super().display_course_info() + f" - Elective Type: {self.elective_type}"