# -*- coding: utf-8 -*-
"""DATA STRUCTURES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uflPjAKKsxaV61gyIpWNm_DESYdjXI2T

### ***LISTS***

#***Question 1***
"""

import random as rd
list_of_random_numbers = [rd.randint(1, 9999) for _ in range(5)]

print("List of random numbers:", list_of_random_numbers)

"""# ***Question 2***"""

print("Original List was :", list_of_random_numbers)
list_of_random_numbers.extend([rd.randint(1, 9999) for _ in range(3)])
print("Updated List of random numbers:",list_of_random_numbers)

"""#***Question 3***"""

for index, value in enumerate(list_of_random_numbers):
  print(f"Position : {index} and number is {value}")

"""# *DICTIONARY*

#***Question 1***
"""

Personal_details ={"Name":"John", "Age":"25", "Address":"New york"}
for i in Personal_details:
  print(f"{i}:{Personal_details.get(i)}")

"""#***Question 2***"""

Personal_details.update({"Phone number":"1234567890"})
for i in Personal_details:
  print(f"{i}:{Personal_details.get(i)}")

"""# *SETS*

#***Question 1***
"""

set1 ={1,2,3,4,5}
print("The set is :", set1)

"""# ***Question 2***"""

set1.add(6)
print("Updated set is :", set1)

"""# ***Question 3***"""

print(f"Original set was: {set1}")
set1.remove(3)
print(f"The set after removing 3: {set1}")

"""# ***TUPLES***




#***Question 1***
"""

tuple1=(1,2,3,4,5)
print(type(tuple1))
print("The tuple is",tuple1)

"""# ***Question 2***"""

print(len(tuple1))

