# -*- coding: utf-8 -*-
"""employee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKtD6ifnvW_BxC4tHrfVfu7z6so9t_eu

# **Excercise 2**
"""

class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    def get_name(self):
        return self.name

    def get_salary(self):
        return self.salary