# -*- coding: utf-8 -*-
"""MonthNames

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVraXaRCz1x0HJWpzNvy3_idtQLtWhaS
"""

while True:
  Number = int(input("Enter the number :"))
  if 1<= Number <= 12:
    months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    print(f"The month is {months[Number-1]}")
    break
  else:
    print("Invalid input! Please try again.")

