# -*- coding: utf-8 -*-
"""PoundsToDollars.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUl9_9xI7AXD03-GUOTx-uasbtETbRV3
"""

pounds_amount = float(input("Enter the amount in Pounds (£): "))

dollar_amount = pounds_amount * 1.22

print(f"Currently, £{pounds_amount} equals ${dollar_amount}.")